#!/usr/bin/env bash
# xsettings.sh — publish GNOME's appearance settings over XSETTINGS (xsettingsd).
#
# GNOME's settings daemon tells every app — snaps and Electron apps included —
# which theme, icons, cursor and font to use. bspwm has no such daemon, so e.g.
# the snap Slack showed a different cursor. This feeds xsettingsd the values
# from org.gnome.desktop.interface (Settings / Tweaks).
#
#   xsettings.sh          write the config and (re)start xsettingsd
#   xsettings.sh --watch  same, then keep it in sync with setting changes

conf="${XDG_CONFIG_HOME:-$HOME/.config}/xsettingsd/xsettingsd.conf"

get() { gsettings get org.gnome.desktop.interface "$1" 2>/dev/null | sed -E "s/^'(.*)'$/\1/"; }

write_conf() {
    local font
    font=$(get font-name | sed -E 's/ @.*//')   # "Ubuntu Sans Medium 11 @wght=500" → Pango name
    mkdir -p "$(dirname "$conf")"
    cat > "$conf.tmp" <<EOF
# Generated by ~/.config/bspwm/xsettings.sh from GNOME's settings — do not edit.
Net/ThemeName "$(get gtk-theme)"
Net/IconThemeName "$(get icon-theme)"
Gtk/CursorThemeName "$(get cursor-theme)"
Gtk/CursorThemeSize $(get cursor-size)
Gtk/FontName "$font"
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
EOF
    mv "$conf.tmp" "$conf"
}

write_conf
if pgrep -u "$USER" -x xsettingsd >/dev/null; then
    pkill -u "$USER" -HUP -x xsettingsd          # reload the config
else
    xsettingsd -c "$conf" >/dev/null 2>&1 &
fi

if [ "${1:-}" = --watch ]; then
    gsettings monitor org.gnome.desktop.interface 2>/dev/null |
    while read -r _; do
        while read -r -t 0.3 _; do :; done          # bursts of changes
        write_conf
        pkill -u "$USER" -HUP -x xsettingsd
    done
fi
