#!/usr/bin/env python3
"""Generates polybar/config.ini.

Nerd Font glyphs are written as code points here so they survive editors and
copy-paste; edit this file and re-run it rather than editing config.ini.

Layout: rounded groups ("pills") on a transparent bar, Catppuccin Latte.
  left    desktops that have windows (focused one in blue)
          system: CPU usage+temp · GPU usage+temp · RAM (click: btop)
  center  date and time
  right   keyboard · volume · brightness · battery · network · bluetooth
          tray, then notifications toggle + power menu
"""
import re
from pathlib import Path

G = {k: chr(v) for k, v in {
    "lcap": 0xE0B6, "rcap": 0xE0B4,
    # clock: Font Awesome, like the chip icons
    "clock": 0xF017, "kbd": 0xF030C, "power": 0xF0425,
    "max": 0xF0293,  # fullscreen-ish arrows, for monocle
    "vol0": 0xF057F, "vol1": 0xF0580, "vol2": 0xF057E, "mute": 0xF075F,
    "bri0": 0xF00DE, "bri1": 0xF00DF, "bri2": 0xF00E0,
    "bat0": 0xF007A, "bat1": 0xF007C, "bat2": 0xF007E, "bat3": 0xF0080,
    "bat4": 0xF0079, "charging": 0xF0084, "plug": 0xF06A5,
    "eth": 0xF0200, "wifi_off": 0xF092E,
    # Same chip glyph as the catppuccin tmux cpu/gpu/ram modules.
    "cpu": 0xF2DB, "mem": 0xF2DB,
    "wifi0": 0xF091F, "wifi1": 0xF0922, "wifi2": 0xF0925, "wifi3": 0xF0928,
}.items()}

PILL = "${colors.surface0}"


def icon(color: str, glyph: str) -> str:
    """Coloured icon in the icon font, followed by a space."""
    return f"%{{F{color}}}%{{T2}}{glyph}%{{T-}}%{{F-}} "


def cap(side: str) -> str:
    """Rounded end of a pill, drawn in the pill colour on the transparent bar."""
    return f"%{{T3}}%{{F{PILL}}}{G[side + 'cap']}%{{F-}}%{{T-}}"


def ws(fg: str, underline: str = "") -> str:
    u = f"%{{u{underline}}}%{{+u}}" if underline else ""
    end = "%{-u}" if underline else ""
    return f"{u}%{{F{fg}}}%name%%{{F-}}{end}"


# Modules inside a pill share its background; caps are their own modules so
# a group still closes cleanly when one of its modules is hidden.
# internal/network has no click-left setting, so clicks are action tags.
NMTUI = "~/.config/polybar/scripts/network.sh"


def on_click(text: str, cmd: str) -> str:
    return f"%{{A1:{cmd}:}}{text}%{{A}}"


WLAN_UP = on_click("%{F${colors.teal}}%{T2}<ramp-signal>%{T-}%{F-} <label-connected>", NMTUI)
WLAN_DOWN = on_click(icon("${colors.overlay1}", G["wifi_off"]) + "<label-disconnected>", NMTUI)
BTOP = "alacritty --class floating-term,floating-term -e btop"
# System pill: orange CPU (usage + temp), purple GPU (usage + temp), blue RAM.
CPU = on_click(icon("${colors.peach}", G["cpu"]) + "<label>", BTOP)
MEM = on_click(icon("${colors.blue}", G["mem"]) + "<label>", BTOP)
ETH_UP = on_click(icon("${colors.teal}", G["eth"]) + "<label-connected>", NMTUI)

IN_PILL = f"format-background = {PILL}\nformat-padding = 1"

cfg = f"""; ============================================================
;  polybar — Catppuccin Latte (generated by scripts/gen-polybar.py)
; ============================================================

[colors]
base      = #eff1f5
mantle    = #e6e9ef
crust     = #dce0e8
text      = #4c4f69
subtext1  = #5c5f77
subtext0  = #6c6f85
overlay2  = #7c7f93
overlay1  = #8c8fa1
overlay0  = #9ca0b0
surface2  = #acb0be
surface1  = #bcc0cc
surface0  = #ccd0da
rosewater = #dc8a78
flamingo  = #dd7878
pink      = #ea76cb
mauve     = #8839ef
red       = #d20f39
maroon    = #e64553
peach     = #fe640b
yellow    = #df8e1d
green     = #40a02b
teal      = #179299
sky       = #04a5e5
sapphire  = #209fb5
blue      = #1e66f5
lavender  = #7287fd
transparent = #00000000

; ============================================================

[bar/main]
monitor = ${{env:MONITOR:}}
width    = 100%:-24
offset-x = 12
offset-y = 8
height   = 26
fixed-center = true
wm-restack = bspwm

; Transparent bar: only the pills are drawn, like the tmux status line.
background = ${{colors.transparent}}
foreground = ${{colors.text}}
line-size  = 2

padding = 0
module-margin = 0

; T1 text, T2 icons, T3 pill caps (sized to fill the bar height)
font-0 = MartianMono Nerd Font Mono:style=Bold:size=10;3
; Propo: icons get their full width, so the next character does not clip them.
font-1 = MartianMono Nerd Font Propo:style=Bold:size=11;3
font-2 = MartianMono Nerd Font Mono:size=19;5
font-3 = Noto Color Emoji:scale=10;2

modules-left   = lcap bspwm rcap gap lcap cpu cputemp gpu memory rcap
modules-center = lcap date rcap
modules-right  = lcap xkeyboard pulseaudio backlight battery wlan eth bluetooth rcap gap tray gap lcap powerprofile notifications power rcap

cursor-click  = pointer
cursor-scroll = ns-resize
enable-ipc = true

; ============================================================
; Pill pieces

[module/lcap]
type = custom/text
format = "{cap('l')}"

[module/rcap]
type = custom/text
format = "{cap('r')}"

[module/gap]
type = custom/text
format = "  "

; ============================================================
; Left

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
; Only desktops with windows are listed; Super+N still reaches all ten.
label-focused  = "{ws('${colors.blue}')}"
label-occupied = "{ws('${colors.subtext0}')}"
label-urgent   = "{ws('${colors.red}')}"
label-empty    =
; Shown while the desktop is maximized (monocle, Super+M / Super+Z).
label-monocle = "{icon('${colors.lavender}', G['max']).strip()}"
label-tiled =
label-focused-padding  = 1
label-occupied-padding = 1
label-urgent-padding   = 1
format = <label-state><label-mode>
format-background = {PILL}

; ============================================================
; Left: system (CPU/RAM/GPU moved here from the tmux status bar)

[module/cpu]
; "<orange icon> usage" — the CPU temperature module follows right after it.
type = internal/cpu
format = "{CPU}"
label = %percentage%%
format-background = {PILL}
format-prefix = " "

[module/cputemp]
type = custom/script
exec = ~/.config/polybar/scripts/cputemp.sh
click-left = {BTOP} &
format = <label>
format-background = {PILL}
format-padding = 1

[module/memory]
type = internal/memory
format = "{MEM}"
label = %percentage_used%%
{IN_PILL}

[module/gpu]
type = custom/script
exec = ~/.config/polybar/scripts/gpu.sh
click-left = {BTOP} &
format-background = {PILL}
format-padding = 1

; ============================================================
; Center

[module/date]
type     = internal/date
interval = 5
date     = %a %d %b
time     = %H:%M
date-alt = %A, %d %B %Y
time-alt = %H:%M
format = "{icon('${colors.blue}', G['clock'])}<label>"
label  = %date%  %time%
{IN_PILL}

; ============================================================
; Right: system status

[module/xkeyboard]
type = internal/xkeyboard
; Click to switch layout. Shows CAPS while Caps Lock is on.
format = "{icon('${colors.lavender}', G['kbd'])}<label-layout><label-indicator>"
label-layout = %layout%
label-indicator-on-capslock = " CAPS"
label-indicator-on-capslock-foreground = ${{colors.red}}
label-indicator-off =
blacklist-0 = num lock
blacklist-1 = scroll lock
{IN_PILL}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false
; Scroll: volume. Click: mute. Right-click: mixer.
format-volume = "%{{F${{colors.sapphire}}}}%{{T2}}<ramp-volume>%{{T-}}%{{F-}} <label-volume>"
format-muted  = "{icon('${colors.red}', G['mute'])}<label-muted>"
label-volume = %percentage%%
label-muted  = muted
label-muted-foreground = ${{colors.overlay1}}
ramp-volume-0 = {G['vol0']}
ramp-volume-1 = {G['vol1']}
ramp-volume-2 = {G['vol2']}
click-right = pavucontrol &
format-volume-background = {PILL}
format-volume-padding = 1
format-muted-background = {PILL}
format-muted-padding = 1

[module/backlight]
type = internal/backlight
; Notebook panel. Missing in the VM, where polybar simply hides the module.
card = intel_backlight
use-actual-brightness = true
enable-scroll = false
format = "%{{F${{colors.yellow}}}}%{{T2}}<ramp>%{{T-}}%{{F-}} <label>"
label = %percentage%%
ramp-0 = {G['bri0']}
ramp-1 = {G['bri1']}
ramp-2 = {G['bri2']}
{IN_PILL}

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
; 101 = never "full" just by percentage. The plug icon then only shows when
; the battery itself reports Full / Not charging, i.e. on the charger.
full-at = 101
low-at  = 15
time-format = %-Hh%M
format-charging    = "{icon('${colors.green}', G['charging'])}<label-charging>"
format-discharging = "%{{F${{colors.green}}}}%{{T2}}<ramp-capacity>%{{T-}}%{{F-}} <label-discharging>"
format-full        = "{icon('${colors.green}', G['plug'])}<label-full>"
format-low         = "{icon('${colors.red}', G['bat0'])}<label-low>"
label-charging    = %percentage%%
label-discharging = %percentage%% %{{F${{colors.overlay1}}}}%time%%{{F-}}
label-full        = full
label-low         = %percentage%% %time%
label-low-foreground = ${{colors.red}}
ramp-capacity-0 = {G['bat0']}
ramp-capacity-1 = {G['bat1']}
ramp-capacity-2 = {G['bat2']}
ramp-capacity-3 = {G['bat3']}
ramp-capacity-4 = {G['bat4']}
format-charging-background = {PILL}
format-charging-padding = 1
format-discharging-background = {PILL}
format-discharging-padding = 1
format-full-background = {PILL}
format-full-padding = 1
format-low-background = {PILL}
format-low-padding = 1

[module/wlan]
type = internal/network
interface-type = wireless
format-connected    = "{WLAN_UP}"
format-disconnected = "{WLAN_DOWN}"
label-connected    = %essid:0:14:…%
label-disconnected = offline
label-disconnected-foreground = ${{colors.overlay1}}
ramp-signal-0 = {G['wifi0']}
ramp-signal-1 = {G['wifi1']}
ramp-signal-2 = {G['wifi2']}
ramp-signal-3 = {G['wifi3']}
format-connected-background = {PILL}
format-connected-padding = 1
format-disconnected-background = {PILL}
format-disconnected-padding = 1

[module/eth]
type = internal/network
interface-type = wired
format-connected = "{ETH_UP}"
label-connected = wired
format-disconnected =
format-connected-background = {PILL}
format-connected-padding = 1

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
click-left = blueman-manager &
format-background = {PILL}
format-padding = 1

; ============================================================
; Right: tray and session

[module/tray]
type = internal/tray
tray-size = 60%
tray-spacing = 8px

[module/powerprofile]
type = custom/script
exec = ~/.config/polybar/scripts/powerprofile-bar.sh
tail = true
click-left = ~/.config/rofi/scripts/powerprofile.sh &
format-background = {PILL}
format-padding = 1

[module/notifications]
type = custom/script
exec = ~/.config/polybar/scripts/notifications.sh
tail = true
click-left = dunstctl set-paused toggle; pkill -USR1 -f '^bash .*polybar/scripts/notifications\\.sh'
format-background = {PILL}
format-padding = 1

[module/power]
type = custom/text
format = "%{{F${{colors.red}}}}%{{T2}}{G['power']}%{{T-}}%{{F-}}"
click-left = ~/.config/rofi/scripts/powermenu.sh &
{IN_PILL}

[settings]
screenchange-reload = true
pseudo-transparency = false
"""

# polybar only expands ${colors.x} for whole values, not inside %{F...} tags,
# so resolve every reference to its hex value.
palette = dict(re.findall(r"^(\w+)\s*=\s*(#[0-9a-fA-F]+)$", cfg.split("[bar/main]")[0], re.M))
head, rest = cfg.split("[bar/main]")
cfg = head + "[bar/main]" + re.sub(r"\$\{colors\.(\w+)\}", lambda m: palette[m[1]], rest)

out = Path(__file__).resolve().parent.parent / "polybar" / "config.ini"
out.write_text(cfg)
print(f"wrote {out}")
